<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>x86</Platforms>
    <!-- See BrokenPlugin.csproj for the AppendPlatformToOutputPath rationale. -->
    <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
    <LangVersion>7.3</LangVersion>
    <IsPackable>false</IsPackable>
    <RootNamespace>UtinniCoreDotNet.Tests.Fixtures.GoodPlugin</RootNamespace>
    <AssemblyName>GoodPlugin</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\UtinniCoreDotNet\UtinniCoreDotNet.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
