/**
 * MIT License
 *
 * Copyright (c) 2020 Philip Klatt
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
**/

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace UtinniCoreDotNetGen
{
    // Phase 3 R-F (per 03-CONTEXT D-22 + PATTERNS.md §"R-F CppSharp header
    // auto-discovery"): walk UtinniCore/ recursively and collect every *.h file
    // for CppSharp projection, excluding any header beneath a path segment named
    // "_internal" (case-insensitive). Convention: any header that should NOT be
    // projected to the managed side lives under an _internal/ directory.
    //
    // CON-O-05 disposition (D-24): StdEdited.cs is the only hand-curated
    // Generated/ file. CppSharp's STL-template handling for std::basic_string is
    // unreliable so StdEdited.cs is curated by hand; the R-F auto-discovery
    // regenerates ONLY Generated/UtinniCore.cs. Std.cs (generated by the
    // UtinniCore-Symbols project) is out of scope. Criteria for keeping a
    // binding hand-curated in StdEdited.cs: (a) CppSharp generates incorrect
    // output for the symbol, OR (b) the symbol name is unstable across MSVC
    // versions, OR (c) the binding requires marshaling logic CppSharp cannot
    // infer. Phase 3 itself adds zero _internal/ directories -- moving any
    // existing header into _internal/ is a follow-up cleanup if it becomes
    // useful.
    //
    // Returns header paths RELATIVE to utinniCoreRoot, with backslash separators
    // (CppSharp's module.Headers.Add API expects this format).
    //
    // Lives in its own file (not Program.cs) so UtinniCoreDotNet.Tests can link
    // it via <Compile Include="..\UtinniCoreDotNetGen\HeaderDiscovery.cs"
    // Link="..." /> -- same lightweight precedent as SlnDirResolver.cs which the
    // Tests project already pulls in (UtinniCoreDotNetGen targets x64/AnyCPU
    // because its CppSharp deps are AMD64; the Tests project runs x86, so a
    // ProjectReference would JIT-explode with BadImageFormatException).
    public static class HeaderDiscovery
    {
        public static List<string> Discover(string utinniCoreRoot)
        {
            var results = new List<string>();
            // Normalize: strip any trailing directory separator so the
            // Substring(prefixLen) trim below is consistent.
            string root = utinniCoreRoot.TrimEnd(
                Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            int prefixLen = root.Length + 1;

            foreach (string headerPath in Directory.EnumerateFiles(
                root, "*.h", SearchOption.AllDirectories))
            {
                string relPath = headerPath.Substring(prefixLen);
                // Exclude any header whose path contains a segment named
                // "_internal" (case-insensitive, matches at any depth). Both
                // forward and back slashes are tolerated so this works under
                // Windows path separators and under any future cross-platform
                // build (current target is Windows-only per CON-P-01).
                bool isInternal = relPath
                    .Split('\\', '/')
                    .Any(seg => string.Equals(seg, "_internal", StringComparison.OrdinalIgnoreCase));
                if (isInternal)
                {
                    continue;
                }
                // CppSharp expects backslash-separated relative paths.
                results.Add(relPath.Replace('/', '\\'));
            }
            return results;
        }
    }
}
