/**
 * MIT License
 *
 * Copyright (c) 2020 Philip Klatt
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
**/

using System;
using System.IO;
using CppSharp;
using CppSharp.AST;
using CppSharp.Generators;

namespace UtinniCoreDotNetGen
{
    public class Program
    {
        class Gen : ILibrary
        {
            private readonly string[] _args;

            public Gen(string[] args)
            {
                _args = args;
            }

            public void Setup(Driver driver)
            {
                string workingDir = AppDomain.CurrentDomain.BaseDirectory;
                string buildMode = new DirectoryInfo(workingDir).Name;
                // C-15: replaced brittle Substring(0, workingDir.LastIndexOf("\\bin\\"))
                // which threw InvalidOperationException when \bin\ was not in the path
                // (e.g. CI runner output paths, env-var fallback). SlnDirResolver supports
                // three resolution modes: args[0], walk-up to Utinni.sln, UTINNI_SLN_DIR env var.
                string slnDir = SlnDirResolver.Resolve(workingDir, _args);

                driver.ParserOptions.TargetTriple = "i686-pc-win32-msvc"; // Generates x86 EntryPoints

                // Needed for spdlog to work
                driver.ParserOptions.UnityBuild = true;
                driver.ParserOptions.EnableRTTI = true;
                driver.ParserOptions.AddDefines("SPDLOG_NO_EXCEPTIONS");
                driver.ParserOptions.AddDefines("FMT_EXCEPTIONS=0");

                var options = driver.Options;
                options.GeneratorKind = GeneratorKind.CSharp;
                options.OutputDir = slnDir + "UtinniCoreDotNet\\Generated\\";
                options.GenerateDebugOutput = false;

                options.SystemModule.SymbolsLibraryName = "UtinniCore-Symbols";

                string targetProjName = "UtinniCore";
                var module = options.AddModule(targetProjName);

                // Includes
                module.IncludeDirs.Add(slnDir);
                module.IncludeDirs.Add(slnDir + "external");
                module.IncludeDirs.Add(slnDir + targetProjName); // ToDo make this a loop to grab all the subfolders

                // Headers -- Phase 3 R-F (per 03-CONTEXT D-22 + D-24): auto-
                // discover every *.h beneath UtinniCore/, excluding any header
                // beneath an _internal/ directory. Replaces the previous explicit
                // ~23-entry allowlist which silently lost newly-added headers
                // (TD-21). The HeaderDiscovery helper above documents the
                // CON-O-05 disposition (StdEdited.cs hand-curated; not
                // regenerated by this glob).
                string utinniCoreRoot = Path.Combine(slnDir, targetProjName);
                foreach (string relHeader in HeaderDiscovery.Discover(utinniCoreRoot))
                {
                    module.Headers.Add(relHeader);
                }

                // Library
                module.LibraryDirs.Add(slnDir + "bin\\" + buildMode + "\\");
                module.Libraries.Add(targetProjName + ".dll");
            }

            public void SetupPasses(Driver driver)
            {
            }

            public void Preprocess(Driver driver, ASTContext ctx)
            {
                ctx.IgnoreHeadersWithName("spdlog");
                ctx.IgnoreHeadersWithName("detourxs");
                ctx.IgnoreHeadersWithName("ADE32");
                // Phase 3 R-F (D-22): the auto-discovery glob picks up every
                // *.h beneath UtinniCore/ now, including headers that the
                // previous explicit allowlist intentionally omitted. The
                // ignore-list below covers headers that produce broken
                // CppSharp output OR transitively depend on swg::WString,
                // which is itself unprojectable:
                //
                //   swg_string: declares overloaded ctors for both wchar_t*
                //     and char16_t* (both project to `string` in C#) plus
                //     identical operator overloads for the same types --
                //     CppSharp emits duplicate C# methods, CS0111.
                //   command_parser / utinni_command_parser: publicly expose
                //     swg::WString fields/parameters; transitively unprojectable.
                //   ui_textbox: setLocalText(const swg::WString&) -- same.
                //
                // Until these headers are migrated under their respective
                // _internal/ subdirectories as a follow-up cleanup (per D-22
                // the _internal/ convention is the canonical hiding mechanism;
                // Phase 3 itself moves zero headers), ignore by name -- same
                // disposition as the spdlog/detourxs/ADE32 entries above.
                ctx.IgnoreHeadersWithName("swg_string");
                ctx.IgnoreHeadersWithName("command_parser");
                ctx.IgnoreHeadersWithName("utinni_command_parser");
                ctx.IgnoreHeadersWithName("ui_textbox");
                // WR-03 (03-REVIEW): game_test_internal.h declares the
                // test-only Game registry accessors (triggerInstallCallbacks,
                // getInstallSubscriberCount). It is consumed ONLY by
                // test_exports.cpp; the managed bindings reach the same
                // functionality via the utinni_test_* P/Invoke exports.
                // Excluding it here keeps the test-only seam out of the
                // generated UtinniCore.cs surface.
                ctx.IgnoreHeadersWithName("game_test_internal");
                // string_utility.h declares a `constexpr static const char*
                // trimableChars` global; CppSharp projects it as a property
                // getter that calls `CppSharp.SymbolResolver.ResolveSymbol`,
                // but UtinniCoreDotNet does not reference CppSharp.dll
                // (CppSharp is a build-time dep of UtinniCoreDotNetGen only).
                // Result: unresolved reference at compile time. Same
                // disposition -- ignore until follow-up _internal/ migration.
                ctx.IgnoreHeadersWithName("string_utility");
            }

            public void Postprocess(Driver driver, ASTContext ctx)
            {
            }
        }

        static void Main(string[] args)
        {
            ConsoleDriver.Run(new Gen(args));
            //Console.Read();
        }
    }
}
