/**
 * MIT License
 *
 * Copyright (c) 2020 Philip Klatt
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
**/

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace UtinniCoreDotNet.Tests
{
    // Phase 17 CPPS-04a — BCL-only (SHA256) per-block-hash ABI surface diff over the
    // freshly-regenerated UtinniCoreDotNet/Generated/UtinniCore.cs.
    //
    // WHY a per-block SET hash and not a whole-file diff:
    // CppSharp reorders the generated file on every build (the documented
    // `git checkout -- Generated/UtinniCore.cs` churn). A whole-file byte diff is pure
    // noise, so a real removed/re-signatured public member or a changed native EntryPoint
    // would slip through and detonate every pre-built plugin DLL at MEF compose on inject
    // (RESEARCH Pitfall 2). A SET of normalized per-block SHA256 hashes is
    // order-independent: reorder churn yields the IDENTICAL set, but a real public-surface
    // change (added / removed / re-signatured member, or a changed DllImport EntryPoint
    // mangled string — the native-ABI anchor) changes the set and the diff trips.
    //
    // The extracted blocks key the public surface on:
    //   - namespace + class/struct/enum FQN (the public type identity)
    //   - public method/property signatures (name + param types + return type)
    //   - every [DllImport(... EntryPoint="<mangled>")] string (a mangled-name change IS
    //     an ABI change — this is the native-ABI anchor)
    //   - public enum members and [FieldOffset(N)] field layout
    //
    // Excluded: the <auto-generated> banner and any ordering-only artifact. There is NO
    // CppSharp version line in the banner to key off (verified — regen-bindings.md was
    // stale claiming one; do not look for it).
    //
    // BCL-only by deliberate choice (CONTEXT Claude's-Discretion default): System.Security
    // .Cryptography.SHA256 + line/regex extraction, NO new NuGet dependency. Escalate to
    // Roslyn only if line-based extraction proves brittle (it has not).
    public static class AbiBlockHash
    {
        // ----- public-surface block extraction patterns -----

        // The native-ABI anchor: [DllImport(..., EntryPoint="<mangled>")]. A mangled-name
        // change IS an ABI change, so the EntryPoint string is hashed verbatim.
        private static readonly Regex EntryPointRegex =
            new Regex("EntryPoint\\s*=\\s*\"(?<ep>[^\"]+)\"", RegexOptions.Compiled);

        // Public type declarations (the namespace+class FQN identity). CppSharp emits
        // "public unsafe partial class X", "public partial struct X", "public enum X",
        // "public partial class X : IDisposable", etc. We capture the kind + name (+ any
        // base list / modifiers) but NOT the line's surrounding position.
        private static readonly Regex PublicTypeRegex = new Regex(
            "^\\s*public\\s+(?:unsafe\\s+|sealed\\s+|abstract\\s+|static\\s+|partial\\s+)*" +
            "(?<kind>class|struct|enum|interface)\\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)" +
            "(?<rest>[^{]*)",
            RegexOptions.Compiled);

        // Public method / property / field signatures (the managed surface a plugin binds
        // against). CppSharp emits "public static void Foo(...)", "public IntPtr Bar { ... }",
        // "public global::...Type Prop", etc. We require the `public` modifier and a member
        // name; we deliberately drop `internal` __Internal P/Invoke decls here (those are
        // covered structurally by their EntryPoint string instead).
        private static readonly Regex PublicMemberRegex = new Regex(
            "^\\s*public\\s+(?!class\\b|struct\\b|enum\\b|interface\\b)" +
            "(?:static\\s+|virtual\\s+|override\\s+|sealed\\s+|unsafe\\s+|extern\\s+|new\\s+|readonly\\s+|const\\s+)*" +
            "(?<sig>[^;{]*[A-Za-z_][A-Za-z0-9_]*\\s*(?:\\([^;{]*\\))?)",
            RegexOptions.Compiled);

        // [FieldOffset(N)] explicit-layout markers — part of the binary layout contract.
        private static readonly Regex FieldOffsetRegex =
            new Regex("\\[\\s*FieldOffset\\s*\\(\\s*(?<n>\\d+)\\s*\\)\\s*\\]", RegexOptions.Compiled);

        // [StructLayout(... Size = N)] explicit-size markers — also layout-load-bearing.
        private static readonly Regex StructLayoutRegex =
            new Regex("\\[\\s*StructLayout\\s*\\([^\\]]*Size\\s*=\\s*(?<n>\\d+)[^\\]]*\\]", RegexOptions.Compiled);

        // Enum member lines (the binary-ABI integer values a pre-built plugin binds against).
        // CppSharp emits enum members as bare "Name = N," lines that do NOT begin with `public`,
        // so PublicMemberRegex never matches them — an enum renumber/reorder/rename is a real
        // binary-ABI break that would otherwise slip the gate (CR-01). We capture each member
        // name + its explicit value, keyed to the enclosing enum FQN, so any such change moves
        // a hash. Only applied when the current scope is an enum (scopeIsEnum frame).
        private static readonly Regex EnumMemberRegex = new Regex(
            "^\\s*(?<name>[A-Za-z_][A-Za-z0-9_]*)\\s*(?:=\\s*(?<val>-?\\w+))?\\s*,?\\s*$",
            RegexOptions.Compiled);

        // A non-declaration line (blank / comment / attribute) to skip when scanning forward
        // from a [FieldOffset(N)] to its real field declaration (WR-02 — an interposed
        // attribute such as [MarshalAs(...)] must not be mistaken for the field).
        private static readonly Regex AttributeOpenRegex = new Regex("^\\s*\\[", RegexOptions.Compiled);

        /// <summary>
        /// Parse Generated/UtinniCore.cs into a set of normalized public-surface block
        /// hashes. The set is order-independent, so CppSharp's reorder churn is invisible
        /// but any real surface change shifts the set.
        /// </summary>
        public static HashSet<string> Extract(string generatedFilePath)
        {
            if (generatedFilePath == null) throw new ArgumentNullException(nameof(generatedFilePath));
            if (!File.Exists(generatedFilePath))
                throw new FileNotFoundException("Generated file not found", generatedFilePath);

            return ExtractFromText(File.ReadAllText(generatedFilePath));
        }

        /// <summary>
        /// Extraction over raw source text (the test-friendly seam — lets the negative /
        /// synthetic tests feed in-memory snippets without a file on disk).
        /// </summary>
        public static HashSet<string> ExtractFromText(string source)
        {
            var set = new HashSet<string>(StringComparer.Ordinal);
            foreach (var key in ExtractRawKeys(source))
            {
                set.Add(Sha256Hex(key));
            }
            return set;
        }

        /// <summary>
        /// The pre-hash, human-readable public-surface block keys (diagnostic seam — lets a
        /// re-bless / drift investigation see WHICH blocks moved, not just opaque hashes).
        /// </summary>
        public static List<string> ExtractRawKeys(string source)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));

            var keys = new List<string>();

            // Brace-depth scope stack. CppSharp reorders the TYPES in the file on every
            // regen, so a block's identity MUST be its true lexical FQN (namespace + nested
            // type names), NOT its emit position. We push a scope name when a namespace or
            // type declaration opens a brace, and pop it when that brace closes — so every
            // block is attributed to its real enclosing scope regardless of emit order. The
            // resulting SET of (FQN-keyed) blocks is genuinely order-independent.
            var scope = new List<string>();   // current FQN segments (namespace + type names)
            var braceFrame = new List<bool>(); // per open-brace: did it push a scope segment?
            // Parallel to `scope`: is the corresponding scope segment an `enum`? Lets the
            // enum-member extraction path (CR-01) fire only inside an enum block, keyed to the
            // enclosing enum's FQN. Pushed/popped in lockstep with `scope`.
            var scopeIsEnum = new List<bool>();
            // CppSharp emits Allman bracing — a namespace/type declaration's opening '{' is
            // on the NEXT line. Carry the declared scope name forward until its '{' arrives.
            string pendingDeclName = null;
            bool pendingDeclIsEnum = false;
            // WR-03: [StructLayout(... Size=N)] is emitted on the line BEFORE the struct decl,
            // so the struct's own name is not yet on the scope stack at capture time. Stash the
            // pending size and emit STRUCTLAYOUT|<full-struct-FQN>|size=N once the struct name
            // is pushed — so two laid-out structs nested in one type can never collide.
            string pendingLayoutSize = null;

            string[] lines = source.Replace("\r\n", "\n").Split('\n');

            for (int i = 0; i < lines.Length; i++)
            {
                string raw = lines[i];
                // WR-01: blank out string/char literal bodies and comments so a '{'/'}' (or a
                // regex-significant token) inside a literal/comment cannot desync the FQN scope
                // stack. The generated file is clean today, but every downstream FQN depends on
                // balanced braces, so harden it. `rawScrubbed` preserves column positions (it
                // replaces literal/comment content with spaces, not removing it) so the existing
                // raw-based regexes keep matching declaration syntax unchanged.
                string rawScrubbed = ScrubLiteralsAndComments(raw);
                string line = rawScrubbed.Trim();

                if (line.Length == 0) continue;
                // Skip the <auto-generated> banner / pure comment lines (ordering-only
                // artifact; no version line exists to key off). A line that is ONLY a comment
                // scrubs to empty above; a trailing comment is already blanked out.

                string fqnPrefix = scope.Count > 0 ? string.Join(".", scope) + "." : "";
                bool inEnumScope = scopeIsEnum.Count > 0 && scopeIsEnum[scopeIsEnum.Count - 1];

                // Enum-member capture (CR-01): inside an enum body, key each member name + its
                // explicit value to the enclosing enum FQN BEFORE the type/member patterns, so a
                // renumber/reorder/rename of an enum value moves the hash set. The opening-brace
                // line of the enum and a lone closing '}' do not match EnumMemberRegex.
                if (inEnumScope)
                {
                    var em = EnumMemberRegex.Match(line);
                    if (em.Success && em.Groups["name"].Value.Length > 0)
                    {
                        keys.Add("ENUMMEMBER|" + fqnPrefix
                            + em.Groups["name"].Value + "=" + em.Groups["val"].Value);
                        // Maintain the brace stack for this line, then move on — do NOT also try
                        // the type/member patterns on an enum-member line.
                        UpdateBraceScope(rawScrubbed, line, scope, braceFrame, scopeIsEnum,
                            ref pendingDeclName, ref pendingDeclIsEnum, ref pendingLayoutSize);
                        continue;
                    }
                }

                // --- public-surface blocks (recorded BEFORE we mutate the scope stack so a
                //     declaration line is attributed to its ENCLOSING scope) ---

                // EntryPoint anchors — the native ABI. Fully deterministic mangled symbol
                // names; a mangled-name change IS an ABI change. Not scope-qualified (the
                // mangled string already encodes the full native identity). Match against the
                // UNSCRUBBED raw line — the EntryPoint value lives inside a string literal that
                // ScrubLiteralsAndComments deliberately blanks (WR-01), so the scrubbed form
                // would hide the very mangled name we must hash.
                var epMatch = EntryPointRegex.Match(raw);
                if (epMatch.Success)
                {
                    keys.Add("ENTRYPOINT|" + epMatch.Groups["ep"].Value);
                }
                else
                {
                    var foMatch = FieldOffsetRegex.Match(line);
                    if (foMatch.Success)
                    {
                        // WR-02: pair the offset with the next REAL field declaration, not a
                        // hard-assumed i+1. Scan forward skipping blank / comment / attribute
                        // lines (e.g. an interposed [MarshalAs(...)]) so the key tracks the
                        // field's type+name, FQN-qualified so it survives reorder churn.
                        string next = "";
                        for (int k = i + 1; k < lines.Length; k++)
                        {
                            string candScrubbed = ScrubLiteralsAndComments(lines[k]);
                            string cand = candScrubbed.Trim();
                            if (cand.Length == 0) continue;
                            if (AttributeOpenRegex.IsMatch(candScrubbed)) continue;
                            next = Normalize(candScrubbed);
                            break;
                        }
                        keys.Add("FIELDOFFSET|" + fqnPrefix + foMatch.Groups["n"].Value + "|" + next);
                    }
                    else
                    {
                        var slMatch = StructLayoutRegex.Match(line);
                        if (slMatch.Success)
                        {
                            // WR-03: the struct's own name is not yet on the scope stack (its
                            // decl is on a later line). Stash the size and emit the key once the
                            // struct name is pushed, so the key carries the full struct FQN and
                            // two laid-out structs nested in one type cannot collide.
                            pendingLayoutSize = slMatch.Groups["n"].Value;
                        }
                        else
                        {
                            var typeMatch = PublicTypeRegex.Match(rawScrubbed);
                            if (typeMatch.Success)
                            {
                                string kind = typeMatch.Groups["kind"].Value;
                                string name = typeMatch.Groups["name"].Value;
                                string rest = Normalize(typeMatch.Groups["rest"].Value);
                                keys.Add("TYPE|" + kind + "|" + fqnPrefix + name
                                    + (rest.Length > 0 ? "|" + rest : ""));
                            }
                            else
                            {
                                var memberMatch = PublicMemberRegex.Match(rawScrubbed);
                                if (memberMatch.Success)
                                {
                                    string sig = Normalize(memberMatch.Groups["sig"].Value);
                                    if (sig.Length > 0 && sig != "public")
                                    {
                                        keys.Add("MEMBER|" + fqnPrefix + sig);
                                    }
                                }
                            }
                        }
                    }
                }

                // --- scope-stack maintenance (Allman-aware brace counting) ---
                UpdateBraceScope(rawScrubbed, line, scope, braceFrame, scopeIsEnum,
                    ref pendingDeclName, ref pendingDeclIsEnum, ref pendingLayoutSize, keys);
            }

            return keys;
        }

        // Shared Allman-aware scope-stack maintenance for one (literal/comment-scrubbed) line.
        // A namespace or type declaration names a scope; its opening '{' arrives on a later line
        // (Allman). We carry pendingDeclName until that '{' is seen, push the name then, and
        // record on the brace frame whether each '{' pushed a segment so the matching '}' pops
        // it. scopeIsEnum tracks, per pushed segment, whether it is an enum body (CR-01). When a
        // struct with a stashed [StructLayout(Size=N)] is pushed, the deferred STRUCTLAYOUT key
        // is emitted now that the full struct FQN is known (WR-03). This keeps FQNs correct
        // across reorder churn AND across enum/class nesting.
        private static void UpdateBraceScope(
            string rawScrubbed, string line,
            List<string> scope, List<bool> braceFrame, List<bool> scopeIsEnum,
            ref string pendingDeclName, ref bool pendingDeclIsEnum, ref string pendingLayoutSize,
            List<string> keys = null)
        {
            if (pendingDeclName == null)
            {
                var nsDecl = Regex.Match(line, "^namespace\\s+(?<ns>[A-Za-z_][A-Za-z0-9_.]*)\\s*$");
                if (nsDecl.Success)
                {
                    pendingDeclName = nsDecl.Groups["ns"].Value;
                    pendingDeclIsEnum = false;
                }
                else
                {
                    // Any type declaration (public OR internal/private nested, e.g. the
                    // __Internal P/Invoke struct) opens a scope worth tracking so member
                    // and field FQNs beneath it are stable.
                    var anyType = Regex.Match(rawScrubbed,
                        "^\\s*(?:\\[[^\\]]*\\]\\s*)*" +
                        "(?:public\\s+|internal\\s+|private\\s+|protected\\s+|unsafe\\s+|sealed\\s+|abstract\\s+|static\\s+|partial\\s+)*" +
                        "(?<kind>class|struct|interface|enum)\\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)");
                    if (anyType.Success)
                    {
                        pendingDeclName = anyType.Groups["name"].Value;
                        pendingDeclIsEnum = anyType.Groups["kind"].Value == "enum";
                    }
                }
            }

            int opens = CountChar(line, '{');
            int closes = CountChar(line, '}');

            // The first '{' after a pending declaration owns that scope segment.
            if (pendingDeclName != null && opens > 0)
            {
                scope.Add(pendingDeclName);
                braceFrame.Add(true);
                scopeIsEnum.Add(pendingDeclIsEnum);
                // WR-03: emit the deferred [StructLayout(Size=N)] key now that the struct's
                // own name is on the scope stack, so the key carries the full struct FQN.
                if (pendingLayoutSize != null && keys != null && !pendingDeclIsEnum)
                {
                    string structFqn = string.Join(".", scope);
                    keys.Add("STRUCTLAYOUT|" + structFqn + "|size=" + pendingLayoutSize);
                }
                pendingLayoutSize = null;
                pendingDeclName = null;
                pendingDeclIsEnum = false;
                opens--;
            }
            for (int o = 0; o < opens; o++) { braceFrame.Add(false); scopeIsEnum.Add(false); }

            for (int c = 0; c < closes; c++)
            {
                if (braceFrame.Count == 0) break;
                bool ownsScope = braceFrame[braceFrame.Count - 1];
                braceFrame.RemoveAt(braceFrame.Count - 1);
                scopeIsEnum.RemoveAt(scopeIsEnum.Count - 1);
                if (ownsScope && scope.Count > 0)
                {
                    scope.RemoveAt(scope.Count - 1);
                }
            }
        }

        private static int CountChar(string s, char c)
        {
            int n = 0;
            foreach (var ch in s) if (ch == c) n++;
            return n;
        }

        // WR-01: replace the BODY of every string literal, verbatim string, char literal, and
        // comment with spaces (preserving the line's length / column positions) so a '{'/'}' or
        // other brace inside a literal/comment cannot desync the FQN scope stack. The opening
        // and closing delimiters are themselves blanked so they never read as code. CppSharp
        // emits single-line declarations (no multi-line strings / block comments spanning
        // lines), so a per-line scrub is sufficient; a '/* ... */' that closes on the same line
        // is handled, and an unterminated one is blanked to end-of-line conservatively.
        private static string ScrubLiteralsAndComments(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            var sb = new StringBuilder(s.Length);
            int n = s.Length;
            for (int i = 0; i < n; i++)
            {
                char c = s[i];

                // Line comment: blank the rest of the line.
                if (c == '/' && i + 1 < n && s[i + 1] == '/')
                {
                    for (; i < n; i++) sb.Append(' ');
                    break;
                }

                // Block comment: blank through the closing '*/' (or to EOL if unterminated).
                if (c == '/' && i + 1 < n && s[i + 1] == '*')
                {
                    sb.Append(' ');
                    sb.Append(' ');
                    i += 2;
                    while (i < n)
                    {
                        if (s[i] == '*' && i + 1 < n && s[i + 1] == '/')
                        {
                            sb.Append(' ');
                            sb.Append(' ');
                            i += 1; // outer for-loop adds the second increment
                            break;
                        }
                        sb.Append(' ');
                        i++;
                    }
                    continue;
                }

                // Verbatim string: @"...". Inside, "" is an escaped quote.
                if (c == '@' && i + 1 < n && s[i + 1] == '"')
                {
                    sb.Append(' ');
                    sb.Append(' ');
                    i += 2;
                    while (i < n)
                    {
                        if (s[i] == '"')
                        {
                            if (i + 1 < n && s[i + 1] == '"') { sb.Append(' '); sb.Append(' '); i += 2; continue; }
                            sb.Append(' ');
                            break;
                        }
                        sb.Append(' ');
                        i++;
                    }
                    continue;
                }

                // Regular string literal: "...". Backslash escapes the next char.
                if (c == '"')
                {
                    sb.Append(' ');
                    i++;
                    while (i < n)
                    {
                        if (s[i] == '\\' && i + 1 < n) { sb.Append(' '); sb.Append(' '); i += 2; continue; }
                        if (s[i] == '"') { sb.Append(' '); break; }
                        sb.Append(' ');
                        i++;
                    }
                    continue;
                }

                // Char literal: '...'. Backslash escapes the next char.
                if (c == '\'')
                {
                    sb.Append(' ');
                    i++;
                    while (i < n)
                    {
                        if (s[i] == '\\' && i + 1 < n) { sb.Append(' '); sb.Append(' '); i += 2; continue; }
                        if (s[i] == '\'') { sb.Append(' '); break; }
                        sb.Append(' ');
                        i++;
                    }
                    continue;
                }

                sb.Append(c);
            }
            return sb.ToString();
        }

        // Collapse runs of whitespace, trim, and strip ordering-only artifacts so a block's
        // identity is its semantic surface, not its exact source formatting.
        private static string Normalize(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            string collapsed = Regex.Replace(s, "\\s+", " ").Trim();
            // Drop the global:: namespace alias prefix (purely cosmetic — identical surface).
            collapsed = collapsed.Replace("global::", "");
            // Drop a trailing opening brace / semicolon (block-start vs same-line is
            // ordering-only).
            collapsed = collapsed.TrimEnd('{', ';', ' ');
            return collapsed;
        }

        private static string Sha256Hex(string input)
        {
            using (var sha = SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(Encoding.UTF8.GetBytes(input));
                var sb = new StringBuilder(hash.Length * 2);
                foreach (byte b in hash) sb.Append(b.ToString("x2"));
                return sb.ToString();
            }
        }

        // ----- committed baseline I/O -----

        /// <summary>Load a committed baseline block-hash set (one sorted hash per line).</summary>
        public static HashSet<string> LoadBaseline(string baselinePath)
        {
            if (baselinePath == null) throw new ArgumentNullException(nameof(baselinePath));
            if (!File.Exists(baselinePath))
                throw new FileNotFoundException("ABI baseline not found", baselinePath);

            var set = new HashSet<string>(StringComparer.Ordinal);
            foreach (var line in File.ReadAllLines(baselinePath))
            {
                string h = line.Trim();
                if (h.Length == 0 || h.StartsWith("#")) continue;
                set.Add(h);
            }
            return set;
        }

        /// <summary>
        /// Write a baseline block-hash set as a sorted, deterministic text file (the
        /// committed ABI contract snapshot). Sorted so the committed artifact is stable
        /// across regens — only a real surface change moves a line.
        /// </summary>
        public static void SaveBaseline(string baselinePath, HashSet<string> set)
        {
            if (baselinePath == null) throw new ArgumentNullException(nameof(baselinePath));
            if (set == null) throw new ArgumentNullException(nameof(set));

            var sorted = set.OrderBy(h => h, StringComparer.Ordinal).ToList();
            var sb = new StringBuilder();
            sb.Append("# UtinniCore ABI public-surface block-hash baseline (CPPS-04a).\n");
            sb.Append("# Generated by AbiBlockHash --rebless over a freshly-regenerated\n");
            sb.Append("# UtinniCoreDotNet/Generated/UtinniCore.cs. One SHA256 per public-surface\n");
            sb.Append("# block (type FQN / member signature / DllImport EntryPoint / field layout).\n");
            sb.Append("# Order-independent SET — reorder churn is invisible; a real surface change\n");
            sb.Append("# moves a line. Re-bless intentionally with the --rebless lockstep procedure.\n");
            foreach (var h in sorted) sb.Append(h).Append('\n');
            File.WriteAllText(baselinePath, sb.ToString());
        }

        // ----- --rebless entry point -----

        /// <summary>
        /// D-01 re-bless: regenerate the committed baseline from the freshly-regenerated
        /// Generated/UtinniCore.cs AND print the lockstep checklist. Invokable from a
        /// test-only harness or documented manual invocation. Path inputs use env-var +
        /// probe discipline (mirrors SlnDirResolver) — never a hard-coded install path.
        /// </summary>
        /// <param name="generatedFilePath">
        /// Optional explicit path to Generated/UtinniCore.cs. If null, resolves via
        /// UTINNI_GENERATED_CS env var, else a probe walk-up from the current directory.
        /// </param>
        /// <param name="baselinePath">
        /// Optional explicit baseline output path. If null, resolves via UTINNI_ABI_BASELINE
        /// env var, else co-located beside this tool under Fixtures/abi-baseline-blockhashes.txt.
        /// </param>
        /// <param name="writeLine">Output sink for the checklist (defaults to Console.WriteLine).</param>
        public static void Rebless(
            string generatedFilePath = null,
            string baselinePath = null,
            Action<string> writeLine = null)
        {
            writeLine = writeLine ?? Console.WriteLine;

            string gen = ResolveGeneratedPath(generatedFilePath);
            // WR-06: co-anchor the baseline to the SAME tree as the resolved generated file so a
            // --rebless from an unexpected cwd can never write the blessed baseline into a
            // sibling checkout. The baseline is derived from the generated file's repo root.
            string baseline = ResolveBaselinePath(baselinePath, gen);

            var set = Extract(gen);
            SaveBaseline(baseline, set);

            writeLine("");
            writeLine("=== ABI baseline re-blessed (CPPS-04a / D-01) ===");
            writeLine("  source : " + gen);
            writeLine("  baseline: " + baseline + "  (" + set.Count + " block hashes)");
            writeLine("");
            writeLine("LOCKSTEP CHECKLIST — commit ALL of the following together:");
            writeLine("  [ ] 1. Rebuild The Jawa Toolbox (UtinniPlugins, Release|x86) against the");
            writeLine("         current binding surface.");
            writeLine("  [ ] 2. Re-freeze the plugin fixture: copy the freshly-built");
            writeLine("         TheJawaToolboxDotNet.dll into");
            writeLine("         UtinniCoreDotNet.Tests/Fixtures/FrozenPlugin/.");
            writeLine("  [ ] 3. Commit the re-blessed baseline + the re-frozen fixture + the");
            writeLine("         paired UtinniPlugins build artifact TOGETHER (one logical change).");
            writeLine("  [ ] 4. NEVER commit UtinniCoreDotNet/Generated/UtinniCore.cs");
            writeLine("         (git checkout -- it after the regen).");
            writeLine("  [ ] 5. Maintainer live-smoke inject: confirm TJT MEF-composes with no");
            writeLine("         compose errors (the only place a real ABI break ultimately surfaces).");
            writeLine("");
        }

        private static string ResolveGeneratedPath(string explicitPath)
        {
            if (!string.IsNullOrEmpty(explicitPath)) return explicitPath;

            string env = Environment.GetEnvironmentVariable("UTINNI_GENERATED_CS");
            if (!string.IsNullOrEmpty(env)) return env;

            // Probe walk-up from the current directory for UtinniCoreDotNet/Generated/UtinniCore.cs.
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null)
            {
                string candidate = Path.Combine(dir.FullName, "UtinniCoreDotNet", "Generated", "UtinniCore.cs");
                if (File.Exists(candidate)) return candidate;
                dir = dir.Parent;
            }
            throw new FileNotFoundException(
                "Could not resolve Generated/UtinniCore.cs (set UTINNI_GENERATED_CS or run from the repo tree).");
        }

        private static string ResolveBaselinePath(string explicitPath, string resolvedGeneratedPath = null)
        {
            if (!string.IsNullOrEmpty(explicitPath)) return explicitPath;

            string env = Environment.GetEnvironmentVariable("UTINNI_ABI_BASELINE");
            if (!string.IsNullOrEmpty(env)) return env;

            // WR-06: co-anchor to the resolved generated file's repo root. The generated path is
            // <repoRoot>/UtinniCoreDotNet/Generated/UtinniCore.cs, so its repo root is three
            // directories up. Forming the baseline path relative to THAT root (rather than
            // independently walking from cwd and returning the first ancestor whose Fixtures dir
            // merely exists) guarantees the re-blessed baseline lands in the same tree as the
            // regen source — never a sibling checkout.
            if (!string.IsNullOrEmpty(resolvedGeneratedPath))
            {
                try
                {
                    // .../Generated/UtinniCore.cs -> Generated -> UtinniCoreDotNet -> <repoRoot>
                    string repoRoot = Path.GetDirectoryName(   // <repoRoot>
                        Path.GetDirectoryName(                  // <repoRoot>/UtinniCoreDotNet
                            Path.GetDirectoryName(              // .../UtinniCoreDotNet/Generated
                                Path.GetFullPath(resolvedGeneratedPath))));
                    if (!string.IsNullOrEmpty(repoRoot))
                    {
                        return Path.Combine(
                            repoRoot, "UtinniCoreDotNet.Tests", "Fixtures", "abi-baseline-blockhashes.txt");
                    }
                }
                catch
                {
                    // Fall through to the file-existence probe below.
                }
            }

            // Fallback: mirror ResolveGeneratedPath — walk up and require the baseline FILE to
            // exist (not merely its containing directory), so an unexpected cwd cannot resolve to
            // a wrong-tree directory that merely happens to have a Fixtures folder.
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null)
            {
                string candidate = Path.Combine(
                    dir.FullName, "UtinniCoreDotNet.Tests", "Fixtures", "abi-baseline-blockhashes.txt");
                if (File.Exists(candidate)) return candidate;
                dir = dir.Parent;
            }
            throw new FileNotFoundException(
                "Could not resolve the baseline file (set UTINNI_ABI_BASELINE or run from the repo tree).");
        }
    }
}
